import type { Metadata } from "next";
import { Geist, Geist_Mono, Caveat_Brush } from "next/font/google";
import "./globals.css";
import 'remixicon/fonts/remixicon.css'
import Cart from "@/components/cart/cart";
import { LoginDialog } from "@/components/login/loginDialog";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const caveatBrush = Caveat_Brush({
  variable: "--font-caveat_brush",
  subsets: ["latin"],
  weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TW-Pizzas",
  description: "Generated by create next app",
  icons: "/pizza.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  ${caveatBrush.variable} bg-[linear-gradient(rgba(255,255,255,1),rgba(255,255,255,0.8),rgba(255,255,255,1)),url('/background.png')] 
            bg-contain bg-repeat bg-center`}
      >
        {children}
        <Cart />
        <LoginDialog />
      </body>
    </html>
  );
}
